superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name= 'detail'),
    path('new/', views.create, name='create'),
    path('<int:hero_id>/', views.delete, name='delete'),
    path('<int:hero_id>/', views.edit, name='edit'),
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
# class is singular
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero= Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def delete(request, hero_id):
    delete_hero= Superhero.objects.get(hero_id)
    delete_hero.delete()
    return render(request, 'superheroes/delete.html')

def edit(request, hero_id):
    edit_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'edit_hero':edit_hero
    }
    return render(request, 'superheroes:edit.html', context)

superhero_project/superheroes/templates/superheroes/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase:  <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>

    <img src="{% static  'images/wonderwoman.png' %}" alt="My image">

</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Post</title>
</head>
<body>
    <form method = "POST">
        <h2>Are you sure you want to delete created Superhero? "{{object.title}}</h2>

        <button> type ="submit"> Yes, Delete</button>
    </form>

    <a href="{% url'superheroes:delete' %}">Add New Hero</a>

</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Details</title>
</head>
<body>
    <hi>Details Page</hi>
    <ul>

<!--     
        {% for hero in single_hero %}
        <li><h2>{{hero.alter_ego}}</h2></li>
        {% endfor %}
     -->
     {{Superhero.alter_ego}}
     {{Superhero.primary_ability}}
     {{Superhero.secondary_ability}}
     {{Superhero.catchphrase}}

     
    </ul>
    
    <a href ="{% url 'superheroes:edit'%}" >Edit </a>

    <a href ="{% url 'superheroes:delete'%}">Delete</a>


</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <hi>List of Heroes</hi>
    <ul>
        {% for hero in all_heroes %}
        <li><h2>{{hero.name}} - <a href="{%url superheroes:detail' hero.id %}">Click for Details</a></h2></li>
        {% endfor %}

    </ul>
    <a href="{% url'superheroes:create' %}">Add New Hero</a>
</body>
</html>